name: Upload Badge
description: 'Action to create and upload a badge to the repository'

inputs:
  github_token:
    type: string
    description: 'GitHub token for authentication'
    required: true
  label:
    type: string
    description: 'Badge label'
  message:
    type: string
    description: 'Badge message'
    required: true
  labelColor:
    type: string
    description: 'Label color'
  color:
    type: string
    description: 'Message color'
  logoBase64:
    type: string
    description: 'Base64 encoded logo'
  style:
    type: string
    description: 'Badge style'
  filename:
    type: string
    description: 'Name of the file'
    required: true

runs:
  using: composite

  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      shell: bash
      working-directory: ${{github.action_path}}
      run: npm ci

    # Step 4: Create or replace the badge
    - name: Create badge
      working-directory: ${{github.action_path}}
      shell: bash
      run: |
          node -e "
          const fs = require('fs');
          const { makeBadge, ValidationError } = require('badge-maker')

          const badgeFile = '${{ inputs.filename }}';
          var format = {
            message: '${{ inputs.message }}',
          }

          if ('${{ inputs.label }}') {
            format.label = '${{ inputs.label }}'
          }

          if ('${{ inputs.labelColor }}') {
            format.labelColor = '${{ inputs.labelColor }}'
          }

          if ('${{ inputs.color }}') {
            format.color = '${{ inputs.color }}'
          }

          if ('${{ inputs.logoBase64 }}') {
            format.logoBase64 = '${{ inputs.logoBase64 }}'
          }

          if ('${{ inputs.style }}') {
            format.style = '${{ inputs.style }}'
          }

          const svg = makeBadge(format)
          fs.writeFileSync(badgeFile, svg);
          
          console.log('Badge created successfully:', badgeFile);
          "

    - name: Checkout badges branch
      uses: actions/checkout@v4
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      with:
        ref: badges

    # Step 5: Commit and push the badge
    - name: Commit and push badge
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      shell: bash
      run: |
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "update ${{ inputs.filename }}" && git push