name: Get Changed Terraform Targets
description: 'Action to create and upload a badge to the repository'

inputs:
  working_directory:
    type: string
    description: 'Working directory for the action'

outputs:
  targets:
    description: 'Changed Terraform targets'
    value: ${{ steps.targets.outputs.targets }}

runs:
  using: composite

  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Install dependencies
      shell: bash
      working-directory: ${{github.action_path}}
      run: npm ci

    - name: Get changed Terraform targets
      id: targets
      shell: bash
      working-directory: ${{inputs.working_directory}}
      run: |
        ${{github.action_path}}/parse.js
