# Terraform import blocks for Okta users
# Generated by import.py

import {
  to = okta_user.evan_forevanyeung_com
  id = "00uo7wwgc9Qf4ki1d5d7"
}

import {
  to = okta_user.example_example_com
  id = "00upujw9d4JhgSzAV5d7"
}

