"""Group retrieval and processing functions."""

from typing import List
import sys
from .utils import sanitize_resource_name, sort_entities


async def get_all_groups(okta_manager) -> List:
    print("Fetching all groups from Okta...")
    groups = []
    try:
        group_list, resp, err = await okta_manager.client.list_groups(query_params={"search": "type eq \"OKTA_GROUP\""})
        if err:
            raise Exception(f"Error fetching groups: {err}")
        groups.extend(group_list)
        while resp.has_next():
            group_list, err = await resp.next()
            if err:
                print(f"Warning: Error fetching additional groups: {err}")
                break
            groups.extend(group_list)
        print(f"Successfully retrieved {len(groups)} groups")
        return groups
    except Exception as e:  # noqa: BLE001
        raise Exception(f"Failed to retrieve groups: {str(e)}") from e


async def process_groups(okta_manager):
    """Process groups and generate terraform import blocks."""
    try:
        groups = await get_all_groups(okta_manager)
        if not groups:
            print("No groups found in your Okta organization.")
            return
        groups = sort_entities(groups, 'profile.name')
        output_file = okta_manager.output_dir / "groups.import.tf"
        with open(output_file, 'w') as f:  # noqa: PTH123
            f.write("# Terraform import blocks for Okta groups\n")
            f.write("# Generated by import.py\n\n")
            for group in groups:
                resource_name = sanitize_resource_name(group.profile.name)
                f.write(f"""import {{\n  to = okta_group.{resource_name}\n  id = \"{group.id}\"\n}}\n\n""")
        print(f"Written {len(groups)} group import blocks to {output_file}")
    except Exception as e:  # noqa: BLE001
        print(f"Error processing groups: {str(e)}", file=sys.stderr)
