name: PR Approval
on:
  pull_request:
    branches:
      - main

jobs:
  approve:
    name: Auto-approve changes to Preview
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: changed-files
        run: |
          files=$(git diff --name-only HEAD~1 HEAD -- ':!preview/')
          echo $files

          if [ -z "$files" ]; then
            echo "approve=true" >> $GITHUB_OUTPUT
          else
            echo "approve=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/github-script@v7
        if: ${{ steps.changed-files.outputs.approve == 'true' }}
        with:
          script: |
            const result = await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            })
            console.log(result.status)

      - uses: actions/github-script@v7
        if: ${{ steps.changed-files.outputs.approve == 'false' }}
        with:
          script: |
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            // if review is already approved by bot, dismiss the review
            for (const review of reviews.data) {
              if (review.user.login === 'github-actions[bot]' && review.state === 'APPROVED') {
                const result = await github.rest.pulls.dismissReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  review_id: review.id,
                  message: "Changes to made outside preview directory require approval from a human"
                })
                console.log(result.status)
              }
            }
