name: Approve PR Approval
on:
  pull_request:
    branches:
      - main
    types: [opened] # probably the only one you need


jobs:
  build:
    name: Auto-approve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - id: changed-files
        run: |
          files=$(git diff --name-only HEAD~1 HEAD -- ':!preview/')
          echo $files

          if [ -z "$files" ]; then
            echo "approve=true" >> $GITHUB_OUTPUT
          else
            echo "approve=false" >> $GITHUB_OUTPUT
          fi

      - uses: actions/github-script@v7
        if: ${{ steps.changed-files.outputs.approve == 'true' }}
        with:
          script: |
            const result = await octokit.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            })
            console.log(result.status)
