name: Approve PR Approval
on:
  pull_request:
    branches:
      - main
    types: [opened] # probably the only one you need


jobs:
  build:
    name: Auto-approve
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: changed-files
        run: git show --format= --name-only -- ':!preview/'

      - uses: actions/github-script@v7
        if: false
        with:
          script: |
            const result = await github.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            })
            console.log(result.status)