name: Status on comment

on:
  issue_comment:
    types: [created]

jobs:
  status: 
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
      statuses: write

    steps:
      - name: React to comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });

      - name: 
        uses: actions/github-script@v7
        with: 
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const sha = pr.head.sha;
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: sha,
              state: "success",
              target_url: runUrl, 
              description: "Check passed"
            });
