name: Comment Help

on:
    pull_request:
      types: [opened]

jobs:
    comment_help:
        name: Comment Terraform Apply Help
        runs-on: ubuntu-latest
        steps:
            - run: |
                gh pr comment 13 --body <<EOF
                @ghost Your changes have been tested and approved and are now ready to be merged.

                Comment the text below exactly as shown (without any additional text) to start a Terraform Apply. If there are no issues, your pull request will be automatically merged into the main branch.

                ```
                terraform apply
                ```
                EOF