name: Status on comment

on:
  issue_comment:
    types: [created]

jobs:
  status: 
    if: github.event.issue.pull_request != null
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write

    steps:
      - name: React to comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });

      - name: Get PR and commit SHA
        id: pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: pr } = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            core.setOutput("head_sha", pr.head.sha);

      - name: Create status
        uses: actions/github-script@v7
        with: 
          script: |
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: ${{ steps.pr.outputs.head_sha }},
              state: "pending",
              target_url: runUrl, 
              context: "terraform-apply",
              description: "Pending - in progress"
            });

      - name: Your deployment logic
        id: deploy
        run: |
          echo "simulate success"
          sleep 5s
          # exit 1  # uncomment to simulate failure

      - name: Update status
        uses: actions/github-script@v7
        with: 
          script: |
            const runUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}`;

            github.rest.repos.createCommitStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              sha: ${{ steps.pr.outputs.head_sha }},
              state: "success",
              target_url: runUrl, 
              context: "terraform-apply",
              description: "Successful in 6s"
            });
