name: Pull Request Help

on:
  pull_request:
    types: [opened]

jobs:
  comment_help:
    name: How to run Terraform Apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Write help comment on PR
        uses: actions/github-script@v7
        with: 
          script: |
            var body = `
            ### 👋 Thanks for opening a pull request!
            If this is your first pull request here (or it’s been a while), please take a second to read how we [deploy changes]() to Okta — it’s a little different than what you might be used to. A trimmed down summary is listed below:

            1. **Open a pull request** (you are here)
            Push your branch and open a PR as usual. This will trigger a terraform plan to show what would change.

            2. **Review and Approve**
            Wait for a team member to review and approve the PR. Automated pre-checks should also pass.

            3. **Deploy changes**
            Deploy changes live with  \`/terraform apply\` as a comment on this PR. 
                > If anything goes wrong, rollback with \`/deploy main\`

            4. **Merge after successful apply**
            Once terraform apply succeeds and the status check passes, you can merge the PR to main.
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })
      