name: Comment

on:
  pull_request:
    types: [opened]

jobs:
  comment_help:
    name: How to run Terraform Apply
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with: 
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `${{ github.event.pull_request.user.login }} Your changes have been tested and approved and are now ready to be merged.

              Comment the text below exactly as shown (without any additional text) to start a Terraform Apply. If there are no issues, your pull request will be automatically merged into the main branch.
    
              \`\`\`
              terraform apply
              \`\`\``
            })
          