name: Terraform Plan

on:
  pull_request:

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      statuses: write

    steps:
      - name: Checkout pull request
        uses: actions/checkout@v4
  
      - name: Run Terraform Plan
        run: |
          echo "Running Terraform Plan..."
          # Simulate Terraform Plan (replace with real command)
          sleep 1