name: Okta Preview

on:
  pull_request:
    branches:
      - main
    paths:
      - preview/**
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  auto-approve:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/shared-auto-approve.yaml
    permissions:
      contents: read
      pull-requests: write

  plan:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/shared-terraform-plan.yaml
    with:
      directory: preview
      vars_file: terraform.enc.tfvars.json
    secrets:
      inherit: true
      sops_age_key: ${{ secrets.sops_age_key }}
    permissions:
      pull-requests: write
      statuses: write
      checks: write

  # Terraform apply is ran via the apply.yaml workflow
  # apply:

  merge:
    if: >
      github.event_name == 'pull_request' && 
      github.event.action == 'closed' && 
      github.event.pull_request.merged == true
    uses: ./.github/workflows/shared-merge-unlock.yaml
    with:
      directory: production
      pr_number: ${{ github.event.number }}
      pr_merged: ${{ github.event.pull_request.merged }}
      source_branch: ${{ github.event.pull_request.head.ref }}
      target_branch: ${{ github.event.pull_request.base.ref }}
    secrets: inherit
    permissions:
      pull-requests: write
      contents: write

  revert:
    if: >
      github.event_name == 'pull_request' && 
      github.event.action == 'closed' && 
      github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - name: Handle cancelled PR
        run: |
          echo "PR was closed without merging - performing cleanup"
          # TODO: Add cleanup logic here
