name: Okta Preview

on:
  pull_request:
    branches: 
      - main
    paths: 
      - preview/**
    
  # push:
  #   branches: 
  #     - main
  #   paths: 
  #     - preview/**
  #

env: 
  DIRECTORY: preview

jobs:
  auto-approve:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/shared-auto-approve.yaml
    permissions:
      contents: read
      pull-requests: write

  plan:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/shared-terraform-plan.yaml
    with: 
      directory: preview
    permissions:
      pull-requests: write
      statuses: write
      checks: write

  # Terraform apply is ran via the apply.yaml workflow
  # apply:

  # merge:
  #   if: github.event_name == 'push'
  #   steps:
  #     - name: 
  #       uses: