name: Okta Production

on:
  pull_request:
    branches: 
      - main
    paths: 
      - production/**
    
  # push:
  #   branches: 
  #     - main
  #   paths: 
  #     - production/**
  #

jobs:
  plan:
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/shared-terraform-plan.yaml
    with: 
      directory: production
    secrets:
      TF_TOKEN: ${{ secrets.TF_TOKEN }}
      OKTA_ORG_NAME: ${{ secrets.OKTA_ORG_NAME }} 
      OKTA_BASE_URL: ${{ secrets.OKTA_BASE_URL }} 
      OKTA_API_CLIENT_ID: ${{ secrets.OKTA_API_CLIENT_ID }} 
      OKTA_API_PRIVATE_KEY_ID: ${{ secrets.OKTA_API_PRIVATE_KEY_ID }} 
      OKTA_API_PRIVATE_KEY: ${{ secrets.OKTA_API_PRIVATE_KEY }} 
      OKTA_API_SCOPES: ${{ secrets.OKTA_API_SCOPES }} 
    permissions:
      pull-requests: write
      statuses: write
      checks: write

  # Terraform apply is ran via the apply.yaml workflow
  # apply:

  # merge:
  #   if: github.event_name == 'push'
  #   steps:
  #     - name: 
  #       uses:
