name: Okta Production

on:
  pull_request:
    branches: 
      - main
    paths: 
      - production/**
    types: 
      - opened
      - reopened
      - closed

jobs:
  plan:
    if: github.event_name == 'pull_request' && github.event.action != 'closed'
    uses: ./.github/workflows/shared-terraform-plan.yaml
    with: 
      directory: production
    secrets: inherit
    permissions:
      pull-requests: write
      statuses: write
      checks: write

  # Terraform apply is ran via the apply.yaml workflow
  # apply:

  merge:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: ./.github/workflows/shared-merge-unlock.yaml
    with:
      directory: production
      pr_number: ${{ github.event.number }}
      pr_merged: ${{ github.event.pull_request.merged }}
      source_branch: ${{ github.event.pull_request.head.ref }}
      target_branch: ${{ github.event.pull_request.base.ref }}
    secrets: inherit
    permissions:
      pull-requests: write
      contents: write