name: Auto Approve Changes
on:
  workflow_call:
    inputs:
      runner:
        description: "Runner to use for the job"
        required: false
        default: "ubuntu-latest"
        type: string

jobs:
  approve:
    name: Auto-approve changes
    runs-on: ${{ inputs.runner }}
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            // if review is already approved by bot, do nothing
            for (const review of reviews.data) {
              if (review.user.login === 'github-actions[bot]' && review.state === 'APPROVED') {
                return
              }
            }

            const result = await github.rest.pulls.createReview({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              event: "APPROVE"
            })
            console.log(result.status)

      - uses: actions/github-script@v7
        if: ${{ steps.changed-files.outputs.approve == 'false' }}
        with:
          script: |
            const reviews = await github.rest.pulls.listReviews({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            })

            // if review is already approved by bot, dismiss the review
            for (const review of reviews.data) {
              if (review.user.login === 'github-actions[bot]' && review.state === 'APPROVED') {
                const result = await github.rest.pulls.dismissReview({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  pull_number: context.issue.number,
                  review_id: review.id,
                  message: "Changes made outside preview directory require approval from a human"
                })
                console.log(result.status)
              }
            }
