name: Terraform Apply on Comment

on:
  issue_comment:
    types: [created]

jobs:
  lock: 
    if: github.event.issue.pull_request != null && github.event.comment.body == 'terraform apply' && github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: React to comment
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.reactions.createForIssueComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              comment_id: context.payload.comment.id,
              content: 'eyes'
            });

      - name: Check deployment lock
        uses: github/lock@v2.3.1
        id: lock
        with:
          mode: check
        
      - name: Comment if unable to obtain lock
        if: steps.lock.outputs.locked == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            var body = `
            ⛔ **Failed to acquire deployment lock** — another deployment is currently in progress.

            Only one deployment can run at a time to avoid conflicts. Please wait for the active deployment to complete before trying again.

            🔗 [View the current deployment](${{ steps.lock.outputs.link }})              
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

            // exit early
            core.setFailed('Failed to acquire lock.');
      
      - name: Get deployment lock
        if: steps.lock.outputs.locked == 'false'
        uses: github/lock@v2.3.1
        with:
          mode: lock

  terraform_apply:
    runs-on: ubuntu-latest
    needs: lock
    permissions:
      pull-requests: write
      statuses: write

    steps:
    #   - name: Set commit status to pending
    #     env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       gh api repos/${{ github.repository }}/statuses/${{ github.event.issue.pull_request.head.sha }} \
    #         -f state='pending' -f description='Terraform Apply in progress' -f context='terraform-apply'

      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head    
  
      - name: Run Terraform Apply
        run: |
          echo "Running Terraform Apply..."
          # Simulate Terraform Apply (replace with real command)
          sleep 1

    #   - name: Set commit status to success
    #     if: success()
    #     env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       gh api repos/${{ github.repository }}/statuses/${{ github.event.issue.pull_request.head.sha }} \
    #         -f state='success' -f description='Terraform Apply completed' -f context='terraform-apply'

    #   - name: Set commit status to failure
    #     if: failure()
    #     env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       gh api repos/${{ github.repository }}/statuses/${{ github.event.issue.pull_request.head.sha }} \
    #         -f state='failure' -f description='Terraform Apply failed' -f context='terraform-apply'
