name: Terraform Apply on Comment

on:
  issue_comment:
    types: [created]

jobs:
  lock: 
    if: github.event.issue.pull_request != null && github.event.comment.body == 'terraform apply' && github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Get deployment lock
        uses: github/lock
        id: lock
        continue-on-error: true
        with:
          mode: lock
        
      - name: 
        if: steps.lock.outcome == 'failure'
        uses: actions/github-script@v7
        with:
          script: |
            var body = `
              There is an active deployment blocking. Please try again after that deployment is completed.
              ${{ steps.lock.outputs.link }}
            `

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body
            })

  terraform_apply:
    if: github.event.issue.pull_request != null && github.event.comment.body == 'terraform apply' && github.event.issue.state == 'open'
    runs-on: ubuntu-latest
    needs: lock
    permissions:
      pull-requests: write
      statuses: write

    steps:
    #   - name: Set commit status to pending
    #     env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       gh api repos/${{ github.repository }}/statuses/${{ github.event.issue.pull_request.head.sha }} \
    #         -f state='pending' -f description='Terraform Apply in progress' -f context='terraform-apply'

      - name: Checkout pull request
        uses: actions/checkout@v4
        with:
          ref: refs/pull/${{ github.event.issue.number }}/head    
  
      - name: Run Terraform Apply
        run: |
          echo "Running Terraform Apply..."
          # Simulate Terraform Apply (replace with real command)
          sleep 1

    #   - name: Set commit status to success
    #     if: success()
    #     env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       gh api repos/${{ github.repository }}/statuses/${{ github.event.issue.pull_request.head.sha }} \
    #         -f state='success' -f description='Terraform Apply completed' -f context='terraform-apply'

    #   - name: Set commit status to failure
    #     if: failure()
    #     env:
    #       GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #     run: |
    #       gh api repos/${{ github.repository }}/statuses/${{ github.event.issue.pull_request.head.sha }} \
    #         -f state='failure' -f description='Terraform Apply failed' -f context='terraform-apply'
