name: Upload Badge

on:
  workflow_call:
    inputs:
      label:
        type: string
        description: 'Badge label'
      message:
        type: string
        description: 'Badge message'
        required: true
      labelColor:
        type: string
        description: 'Label color'
      color:
        type: string
        description: 'Message color'
      logoBase64:
        type: string
        description: 'Base64 encoded logo'
      style:
        type: string
        description: 'Badge style'
      filename:
        type: string
        description: 'Name of the file'
        required: true
  workflow_dispatch:
    inputs:
      label:
        description: 'Badge label'
      message:
        description: 'Badge message'
        required: true
      labelColor:
        description: 'Label color'
      color:
        description: 'Message color'
      logoBase64:
        description: 'Base64 encoded logo'
      style:
        description: 'Badge style'
        type: choice
        options:
          - plastic
          - flat
          - flat-square
          - for-the-badge
          - social
      filename:
        description: 'Name of the file'
        required: true

permissions:
  contents: write

jobs:
  create-badge:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: badges

    steps:
      - name: Checkout badges branch
        uses: actions/checkout@v4
        with:
          ref: badges

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      # Step 4: Create or replace the badge
      - name: Create badge
        run: |
            node -e "
            const fs = require('fs');
            const { makeBadge, ValidationError } = require('badge-maker')

            const badgeFile = '${{ inputs.filename }}';
            var format = {
              message: '${{ inputs.message }}',
            }

            if ('${{ inputs.label }}') {
              format.label = '${{ inputs.label }}'
            }

            if ('${{ inputs.labelColor }}') {
              format.labelColor = '${{ inputs.labelColor }}'
            }

            if ('${{ inputs.color }}') {
              format.color = '${{ inputs.color }}'
            }

            if ('${{ inputs.logoBase64 }}') {
              format.logoBase64 = '${{ inputs.logoBase64 }}'
            }

            if ('${{ inputs.style }}') {
              format.style = '${{ inputs.style }}'
            }

            const svg = makeBadge(format)
            fs.writeFileSync(badgeFile, svg);
            
            console.log('Badge created successfully:', badgeFile);
            "

      # Step 5: Commit and push the badge
      - name: Commit and push badge
        run: |
            git config --local user.name "github-actions"
            git config --local user.email "action@github.com"
            git add .
            git diff-index --quiet HEAD || git commit -m "update ${{ inputs.filename }}" && git push