name: Upload Badge

on:
  workflow_dispatch:
    inputs:
      label:
        description: 'Badge label'
        default: 'build'
      message:
        description: 'Badge message'
        required: true
      labelColor:
        description: 'Label color'
        default: '#555'
      color:
        description: 'Message color'
        default: '#4c1'
      logoBase64:
        description: 'Base64 encoded logo'
      style:
        description: 'Badge style'
        default: 'flat'
        type: choice
        options:
          - plastic
          - flat
          - flat-square
          - for-the-badge
          - social
      filename:
        description: 'Name of the file'
        required: true

jobs:
  default:
    run:
      working-directory: badges

  create-badge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout badges branch
        uses: actions/checkout@v4
        with:
          ref: badges

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install badge-maker
        run: npm install badge-maker

      # Step 4: Create or replace the badge
      - name: Create badge
        run: |
            node -e "
            const fs = require('fs');
            const { makeBadge, ValidationError } = require('badge-maker')

            const badgeFile = '${{ github.event.inputs.filename }}';
            
            makeBadge({
              label: '${{ github.event.inputs.label }}',
              message: '${{ github.event.inputs.message }}',
              color: '${{ github.event.inputs.color }}',
              style: '${{ github.event.inputs.style }}'
            })
            .then((svg) => {
              fs.writeFileSync(badgeFile, svg);
            })

            console.log('Badge created successfully:', badgeFile);
            "
