name: Upload Badge

on:
  workflow_dispatch:
    inputs:
      badge_command:
        description: 'Command to generate the badge'
        required: true

jobs:
  create-badge:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.upload.outputs.artifact-name }}

    steps:
      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      # Step 3: Install badge-maker
      - name: Install badge-maker
        run: npm install -g badge-maker

      # Step 4: Create or replace the badge
      - name: Create or replace badge
        id: create_badge
        run: |
          # Create the badges directory if it doesn't exist
          mkdir -p badges

          # Create the badge using the command provided in the workflow dispatch input
          badge_command="${{ github.event.inputs.badge_command }}"
          echo "Running command: $badge_command"
          badge $badge_command | tee badges/badge.svg

      - name: Upload Pages artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: badges

  upload-badge:
    # Add a dependency to the build job
    needs: create-badge

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Specify runner + deployment step
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
